from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


FALSE_VALUES = {"0", "false", "f", "no", "n", "drop", "dropped", "skip", "remove", "ignore"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit annotation review packet completion.")
    parser.add_argument(
        "--packet-index",
        type=Path,
        required=True,
        help="annotation_packet_index.json generated by create_paper_subset_annotation_packets.py.",
    )
    parser.add_argument("--output-json", type=Path, help="Optional JSON status report.")
    parser.add_argument("--output-md", type=Path, help="Optional Markdown status report.")
    return parser.parse_args()


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def _clean(value: Any) -> str:
    return "" if value is None else str(value).strip()


def _is_false(value: Any) -> bool:
    return _clean(value).lower() in FALSE_VALUES


def _pct(done: int, total: int) -> float:
    return round((done / total) * 100.0, 2) if total else 100.0


def _audit_nodes(rows: list[dict[str, str]]) -> dict[str, int]:
    complete = 0
    missing_keep = 0
    missing_review_label = 0
    dropped = 0
    for row in rows:
        keep = _clean(row.get("keep"))
        if not keep:
            missing_keep += 1
            missing_review_label += 1
            continue
        if _is_false(keep):
            dropped += 1
            complete += 1
            continue
        if not _clean(row.get("review_label")):
            missing_review_label += 1
            continue
        complete += 1
    return {
        "total": len(rows),
        "complete": complete,
        "missing_keep": missing_keep,
        "missing_review_label": missing_review_label,
        "dropped": dropped,
    }


def _audit_relations(rows: list[dict[str, str]]) -> dict[str, int]:
    complete = 0
    missing_keep = 0
    missing_review_count = 0
    dropped = 0
    for row in rows:
        keep = _clean(row.get("keep"))
        if not keep:
            missing_keep += 1
            missing_review_count += 1
            continue
        if _is_false(keep):
            dropped += 1
            complete += 1
            continue
        if not _clean(row.get("review_count")):
            missing_review_count += 1
            continue
        complete += 1
    return {
        "total": len(rows),
        "complete": complete,
        "missing_keep": missing_keep,
        "missing_review_count": missing_review_count,
        "dropped": dropped,
    }


def _packet_status(packet: dict[str, Any]) -> dict[str, Any]:
    node_path = Path(str(packet["node_review_csv"]))
    relation_path = Path(str(packet["relation_review_csv"]))
    checked_path = Path(str(packet["packet_dir"])) / "annotation_checked.json"
    node_status = _audit_nodes(_read_csv(node_path))
    relation_status = _audit_relations(_read_csv(relation_path))
    total = node_status["total"] + relation_status["total"]
    complete = node_status["complete"] + relation_status["complete"]
    return {
        "scene_id": packet["scene_id"],
        "packet_dir": packet["packet_dir"],
        "annotation_review_html": packet["annotation_review_html"],
        "node_review_csv": packet["node_review_csv"],
        "relation_review_csv": packet["relation_review_csv"],
        "annotation_checked_json": str(checked_path),
        "annotation_checked_exists": checked_path.exists(),
        "nodes": node_status,
        "relations": relation_status,
        "total_rows": total,
        "complete_rows": complete,
        "completion_percent": _pct(complete, total),
        "ready_for_checked_json": complete == total,
    }


def _markdown(report: dict[str, Any]) -> str:
    rows = report["packets"]
    lines = [
        "# Annotation Review Status",
        "",
        "This report audits the manual review fields required before generating checked annotations.",
        "",
        "| Scene | Nodes complete | Relations complete | Overall | Checked JSON | Review page |",
        "| --- | ---: | ---: | ---: | --- | --- |",
    ]
    for row in rows:
        node = row["nodes"]
        rel = row["relations"]
        checked = "yes" if row["annotation_checked_exists"] else "no"
        lines.append(
            "| `{scene}` | {node_complete}/{node_total} | {rel_complete}/{rel_total} | {pct:.2f}% | {checked} | `{html}` |".format(
                scene=row["scene_id"],
                node_complete=node["complete"],
                node_total=node["total"],
                rel_complete=rel["complete"],
                rel_total=rel["total"],
                pct=row["completion_percent"],
                checked=checked,
                html=row["annotation_review_html"],
            )
        )
    lines.extend(
        [
            "",
            "## Totals",
            "",
            f"- Packets: {report['packet_count']}",
            f"- Node rows complete: {report['node_rows_complete']}/{report['node_rows_total']}",
            f"- Relation rows complete: {report['relation_rows_complete']}/{report['relation_rows_total']}",
            f"- Overall completion: {report['completion_percent']:.2f}%",
            f"- Packets ready for `annotation_checked.json`: {report['ready_packet_count']}/{report['packet_count']}",
            "",
            "A node row is complete when `keep` is filled and, for kept rows, `review_label` is filled.",
            "A relation row is complete when `keep` is filled and, for kept rows, `review_count` is filled.",
        ]
    )
    if report.get("recommended_first_scene"):
        lines.extend(
            [
                "",
                "## Recommended First Scene",
                "",
                f"Start with `{report['recommended_first_scene']}` because it has the smallest remaining review load.",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    index = json.loads(args.packet_index.read_text(encoding="utf-8"))
    packets = [_packet_status(packet) for packet in index.get("packets", [])]
    node_total = sum(packet["nodes"]["total"] for packet in packets)
    node_complete = sum(packet["nodes"]["complete"] for packet in packets)
    relation_total = sum(packet["relations"]["total"] for packet in packets)
    relation_complete = sum(packet["relations"]["complete"] for packet in packets)
    total = node_total + relation_total
    complete = node_complete + relation_complete
    remaining = [packet for packet in packets if not packet["ready_for_checked_json"]]
    recommended = min(remaining, key=lambda packet: packet["total_rows"] - packet["complete_rows"], default=None)
    report = {
        "packet_index": str(args.packet_index),
        "packet_count": len(packets),
        "ready_packet_count": sum(1 for packet in packets if packet["ready_for_checked_json"]),
        "node_rows_total": node_total,
        "node_rows_complete": node_complete,
        "relation_rows_total": relation_total,
        "relation_rows_complete": relation_complete,
        "total_rows": total,
        "complete_rows": complete,
        "completion_percent": _pct(complete, total),
        "recommended_first_scene": recommended["scene_id"] if recommended else "",
        "packets": packets,
    }

    if args.output_json:
        args.output_json.parent.mkdir(parents=True, exist_ok=True)
        args.output_json.write_text(json.dumps(report, indent=2), encoding="utf-8")
        print(f"Wrote {args.output_json}")
    if args.output_md:
        args.output_md.parent.mkdir(parents=True, exist_ok=True)
        args.output_md.write_text(_markdown(report), encoding="utf-8")
        print(f"Wrote {args.output_md}")

    print(
        "completion={pct:.2f}% nodes={node_done}/{node_total} relations={rel_done}/{rel_total} ready_packets={ready}/{count}".format(
            pct=report["completion_percent"],
            node_done=node_complete,
            node_total=node_total,
            rel_done=relation_complete,
            rel_total=relation_total,
            ready=report["ready_packet_count"],
            count=report["packet_count"],
        )
    )
    if report["recommended_first_scene"]:
        print(f"recommended_first_scene={report['recommended_first_scene']}")


if __name__ == "__main__":
    main()
